version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PGDATABASE=postgres
    volumes:
      - odoo_data:/var/lib/odoo
    networks:
      - odoo_network

networks:
  odoo_network:

volumes:
  db_data:
  odoo_data:
