version: '1'

services:
  odoo:
    image: bitnami/odoo:16
    environment:
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_PASSWORD=odoo123
      - ODOO_DATABASE_NAME=bitnami_odoo
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_MASTER_PASSWORD=my_master_password  # Ajoute cette ligne pour définir le mot de passe maître
    ports:
      - "8069:8069"
    depends_on:
      - postgresql
    volumes:
      - odoo_data:/bitnami/odoo

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=bitnami_odoo
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_PASSWORD=odoo123
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  odoo_data:
  postgresql_data:
